spring:
  application:
    name: activity-service

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      database: activitydb
      authentication-database: admin

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
